[project]
name = "pixiv"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=11.2.1",
    "pixivpy3>=3.7.5",
    "pyinstaller>=6.13.0",
    "python-dateutil>=2.9.0.post0",
]
